#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    #url: jdbc:mysql://192.168.159.128/sell?characterEncoding=utf8&useSSL=false
    url: jdbc:mysql://10.0.3.62/sell?characterEncoding=utf8&useSSL=false
  jpa:
    show-sql: true
#项目访问名
server:
  context-path: /sell